# Generated by Django 2.2 on 2020-04-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200430_2300'),
        ('subscriptions', '0002_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriptor',
            field=models.OneToOneField(default='f4726e6a-358a-4749-9271-c5b5cbfee525', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.Subscriptor'),
            preserve_default=False,
        ),
    ]
