# Generated by Django 2.2 on 2020-05-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200430_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriptor',
            new_name='subscriber',
        ),
    ]
