# Generated by Django 2.2 on 2020-04-30 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='co2_tons_per_year',
        ),
        migrations.AddField(
            model_name='customuser',
            name='toroto_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subscriptor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co2_tons_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
