# Generated by Django 2.2 on 2020-04-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200430_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptor',
            name='email',
            field=models.EmailField(default='scqsc"wdcsdc.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptor',
            name='first_name',
            field=models.CharField(default='Unoe', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptor',
            name='last_name',
            field=models.CharField(default='Duoe', max_length=50),
            preserve_default=False,
        ),
    ]
