# Generated by Django 2.2 on 2020-05-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20200501_0051'),
        ('users', '0006_auto_20200430_2328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptor',
            new_name='Subscriber',
        ),
    ]
